Assessing Multi-Class Logistic Regression Model Performance on JUMP Dataset with Various Data Splits Figures
WayScience/Cytotoxic-Nuisance-Metadata-Analysis pull request #8
Opened 2024-04-05 23:55 UTC by axiomcura

This pull request introduces plots generated after evaluating our multi-class logistic regression model and applying it to the JUMP dataset. In the `/notebooks` directory, you will find subfolders that reflect the types of plots generated. Each plot name provides a brief description of its content.

**In the `confusion_matrix` folder:**

- `confusion_matrix.png`: Displays multiple confusion matrices where the columns represent if the dataset was applied to a shuffled model, and the type of dataset split applied to the model. The color indicates the recall per true and predicted class combinations.

- `overlapping_confusion_matrix`: This is generated using JUMP wells that have been labeled by identifying which treatments coincide with the cell injury dataset types.

**In the `f1_score_plot` folder:**

- `f1_score_barplot`: Presents a bar plot where each subplot represents a specific class, and the bars indicate the F1 score. The x-axis represents whether the datasets have been applied to the original or shuffled model.

**In the `pr_curves` folder:**

- `full_pr_curves.png`: Illustrates the PR curves pertaining to all classes and data splits.

- `only_test_train_pr_curve.png`: Shows PR curves for both the train and test sets.

**In the `proba_facet_plot` folder:**

- `JUMP_cell_injury_facet_proba.png`: Demonstrates a facet plot separated by classes and shuffled types. These plots depict the probability density when predicting the types of injury classes within the unlabeled cell injury classes in the JUMP dataset.

2024-04-08 15:11 UTC, MikeLippincott requested changes
Requesting changes for comments made. Please let me know if you have any questions! Good PR.

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/1.data_splits/nbconverted/1.data_splits.py
> +cell_injury_metadata = fs_profile_df[fs_profile_df.columns[:33]]
Consider changing this code to be more dynamic. What if the order of columns change and metadata is no longer in the beginning?

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/2.modeling/nbconverted/2.modeling.py
> +# - **l1_ratio**: The mixing parameter for elastic net regularization. It determines the balance between L1 and L2 penalties in the regularization term. A value of 1 corresponds
`A value of 1 corresponds to`. Consider finishing this sentence

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/2.modeling/nbconverted/2.modeling.py
> +# evaluating model on train dataset
```suggestion
# evaluating shuffled model on test dataset
```

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/2.modeling/nbconverted/2.modeling.py
> +)
to reduce potential typos and DNR, Consider making a dict and looping over the dict with one function.

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/2.modeling/nbconverted/2.modeling.py
> +all_cm_dfs
Nice tidy long format!

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/3.jump-analysis/nbconverted/3.1.overlapping_compounds.py
> +# setting seed =
```suggestion
# setting seed
```

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/3.jump-analysis/nbconverted/3.1.overlapping_compounds.py
> +overlapping_jump_df.head()
Consider using `print(df.shape)` statements to verify that the operation is correct

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/3.jump-analysis/nbconverted/3.jump_analysis.py
> +)
Consider using a more dynamic way of grabbing columns? Order might not always be preserved here

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/4.visualization/confusion_matrix/confusion_matrix.png
Comments for figure:
1. Grey boxes in the verticle direction do not make sense
2. recall of 1 for a count of 0 is hard to understand.
3. Facet labels need underscores removed
4. X axis tick labels need to be trued up to be in line with the tick.
5. Consider switching the order of train and test so that train is on top
6. Capitalization fixes

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/4.visualization/confusion_matrix/confusion_matrix.r
> +ggsave(filename = "confusion_matrix.png", height = height, width = width)
for publication readiness 
```suggestion
ggsave(filename = "confusion_matrix.png", height = height, width = width, dpi=600)
```

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/4.visualization/confusion_matrix/confusion_matrix.r
> +    + ylab("True Class")
```suggestion
    + ylab("True class")
```

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/4.visualization/confusion_matrix/confusion_matrix.r
> +    + xlab("Predicted Class")
```suggestion
    + xlab("Predicted class")
```

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/4.visualization/confusion_matrix/confusion_matrix.r
> +    + ylab("True Class")
```suggestion
    + ylab("True class")
```

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/4.visualization/confusion_matrix/confusion_matrix.r
> +    + xlab("Predicted Class")
```suggestion
    + xlab("Predicted class")
```

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/4.visualization/confusion_matrix/confusion_matrix.r
> +ggsave(filename = "overlapping_confusion_matrix.png", height = height, width = width)
```suggestion
ggsave(filename = "overlapping_confusion_matrix.png", height = height, width = width, dpi=600)
```

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/4.visualization/confusion_matrix/overlapping_confusion_matrix.png
Same here
1. remove underscores 
2. Square up the matrix

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/4.visualization/confusion_matrix/confusion_matrix.r
> +)
```suggestion
    + theme(axis.text.x = element_text(angle = 90, hjust = 1))
    + ggplot2::coor_fixed()
)
```

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/4.visualization/f1_score_plot/f1_score_barplots.png
1. Consider squaring up the plots
2. remove _ from the Legend
3. Flip the X-axis tick labels and the Legend
So Train, test, etc on the x axis and two colours for shuffled and non-shuffled in the legend

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/4.visualization/pr_curves/full_pr_curves.png
1. square each plot. it is a 1:1 comparison on axis
2. Capitalize the legend title and center it
3. remove title
4. Class names are cut off in the facet title
5. Remove underscores from names
6. Flip the order of the train and test facets

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/4.visualization/pr_curves/only_test_train_pr_curve.png
Keep colors consistent.
Last plot the colors were for shuffled or non shuffled now they are for test and train.

Consider making a dashed line or solid line for shuffled models uniform for all plots

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/4.visualization/pr_curves/pr_curves.r
> +ggsave("only_test_train_pr_curve.png", width = width, height = height)
```suggestion
ggsave("only_test_train_pr_curve.png", width = width, height = height, dpi=600)
```
Apply for all

2024-04-08 15:11 UTC, MikeLippincott commented on notebooks/4.visualization/proba_facet_plot/JUMP_cell_injury_facet_proba.png
1. Facet names are cut off
2. This is a smooshed figure it is hard to read 
3. Consider making the shuffled and non shuffled curves a different color and merging into a single facet
then place half of the classed on the top row and the second half on the bottom row. This will spread out the curves and allow for easy reading

2024-04-15 16:19 UTC, MikeLippincott approved these changes
LGTM. Great work with a lot of data and a lot of plots!

2024-04-15 16:19 UTC, MikeLippincott commented on notebooks/4.visualization/confusion_matrix/overlapping_confusion_matrix.png
This plot does not seem to generalize well. Hmmm.

2024-04-15 16:19 UTC, MikeLippincott commented on notebooks/4.visualization/f1_score_plot/f1_score_barplots.png
Y ans x axis text might be increased for improved readability!

2024-04-15 16:19 UTC, MikeLippincott commented on notebooks/4.visualization/pr_curves/full_pr_curves.png
Nonspecific reactive is cut off a bit. Consider increasing the axis and legend font size.

Also keep consistent across plots for order of shuffle colors and legend title (shuffle vs. Shuffle)

2024-04-15 16:19 UTC, MikeLippincott commented on notebooks/4.visualization/pr_curves/only_test_train_pr_curve.png
Consider making the facet text label size larger.

A bit jarring to see shuffle vs non shuffle as blue and red in the previous PR curve and now it represents train vs test.

Consider removing the under score for `dataset_type' and replace with `Data split`

Legend text should be a bit larger too!

Consistency for order of Not Shuffled and shuffled should be verified too!

2024-04-15 16:19 UTC, MikeLippincott commented on notebooks/4.visualization/proba_facet_plot/JUMP_cell_injury_facet_proba.png
Consider making the color the same as previous plots too.

Y axis tick label size should increase as well as the facet text size.

The dashed line at 0.5 might be removed. Up to you.

2024-04-15 16:19 UTC, MikeLippincott commented on notebooks/4.visualization/proba_facet_plot/JUMP_cell_injury_facet_proba.png
For the dashed line, what does having the line provide?

2024-04-15 19:04 UTC, axiomcura commented on notebooks/4.visualization/confusion_matrix/overlapping_confusion_matrix.png
Unfortunately It  doesn't.. Only 3 overlapping treatments were found ( in notebook 3.1)

2024-04-15 22:01 UTC, gwaybio reviewed
I made several comments on modeling - I'll hold off on commenting on the figures, which look like a great start. We can discuss figure strategy in person this week.

2024-04-15 22:01 UTC, gwaybio commented on data/JUMP_data/download.ipynb
> +            "execution_count": null,
Looks like this reverted to null

2024-04-15 22:01 UTC, gwaybio commented on notebooks/1.data_splits/nbconverted/1.data_splits.py
> +from src.utils import split_meta_and_features  # noqa
pycytominer has a function for this (https://pycytominer.readthedocs.io/en/latest/pycytominer.cyto_utils.html#pycytominer.cyto_utils.features.infer_cp_features)

We should probably use this functionality given this is the pycytominer paper.

2024-04-15 22:01 UTC, gwaybio commented on notebooks/2.modeling/nbconverted/2.modeling.py
> +# Below are the paramters used:
Love this documentation!

2024-04-15 22:01 UTC, gwaybio commented on notebooks/2.modeling/nbconverted/2.modeling.py
> +X_train, X_test, y_train, y_test = train_test_split(
This is a minor point (probably to be implemented in the future, and not here), but I would have expected this logic to exist in the data_splits notebook. Really, the data_splits is a holdout split now, since the remaining data splits occur in this notebook.

2024-04-15 22:01 UTC, gwaybio commented on notebooks/2.modeling/nbconverted/2.modeling.py
> +X_train, X_test, y_train, y_test = train_test_split(
It is great to see a random seed here!

2024-04-15 22:01 UTC, gwaybio commented on notebooks/2.modeling/nbconverted/2.modeling.py
> +# creating confusing matrix with plate holdout (shuffled and not snuffled)
```suggestion
# creating confusing matrix with plate holdout (shuffled and not shuffled)
```

2024-04-15 22:01 UTC, gwaybio commented on notebooks/2.modeling/nbconverted/2.modeling.py
> +# creating confusing matrix with plate holdout (shuffled and not snuffled)
(note I make this suggestion in the nbconverted file, so you will actually have to make the change in the corresponding .ipynb and re-nbconvert)

2024-04-15 22:01 UTC, gwaybio commented on notebooks/2.modeling/nbconverted/2.modeling.py
> +# creating confusing matrix with plate_hold (shuffled and not snuffled)
same typo here

2024-04-15 22:01 UTC, gwaybio commented on notebooks/3.jump-analysis/3.1.overlapping_compounds.py
> +# # Finding overlapping compounds
It looks like you're doing more in this notebook than just finding overlapping compounds. You're also applying the pretrained model to these profiles. Consider renaming this notebook to reflect the additional functionality.

I also have some comments about approach:

1. Why not apply the model to all JUMP compounds? (maybe you do this later, and I haven't gotten to review it yet)
2. Why are you downsampling DMSO? Your model is pre-trained, and you are not impacted by data type imbalance during inference.

2024-04-15 22:01 UTC, gwaybio commented on notebooks/3.jump-analysis/3.jump_analysis.py
> +print("Number of shapred features of both profiles", len(aligned_features))
```suggestion
print("Number of shared features of both profiles", len(aligned_features))
```

Also, wow! There are only 207 features in common? Do you know the source of the discrepancy? This is also a really small proportion... we might be able to solve the discrepancy by understanding the differences (maybe there are small differences in naming that we can solve), or, we might need to retrain the models using the smaller subset.

2024-04-15 22:01 UTC, gwaybio commented on notebooks/3.jump-analysis/3.jump_analysis.py
> +# In[12]:
I'm confused about what this dataframe is. It has 1,169,880 rows but there's no identifying information about what each row is - is compound information supposed to be in here somewhere?

2024-04-15 22:01 UTC, gwaybio commented on notebooks/3.jump-analysis/nbconverted/3.1.overlapping_compounds.py
> +#!/usr/bin/env python
It looks like there are two versions of this script (one inside `nbconverted` folder) - are they the same, or have you made changes to one? (only one should exist)

2024-04-15 22:01 UTC, gwaybio commented on notebooks/3.jump-analysis/3.1.overlapping_compounds.py
> +# # Finding overlapping compounds
I see you're applying to all of JUMP in a later analysis. However, it looks like in that all-JUMP notebook, you're doing an extensive analysis on feature overlap (which you should) - why isn't this feature overlap consideration important in this notebook?

2024-04-15 22:01 UTC, gwaybio commented on notebooks/3.jump-analysis/3.1.overlapping_compounds.py
> +# # Finding overlapping compounds
Also, if you're making predictions in that other notebook, aren't you applying th models to these overlapping samples twice?

2024-04-15 22:01 UTC, gwaybio commented on notebooks/3.jump-analysis/nbconverted/3.jump_analysis.py
> +# In[1]:
same comment about duplicate nbconverted files

2024-04-15 23:31 UTC, axiomcura commented on notebooks/3.jump-analysis/3.jump_analysis.py
> +# In[12]:
These are the probabilities generated from the trained model in tidy long format. Hence, the 1.2 million rows.

2024-04-15 23:45 UTC, axiomcura commented on notebooks/3.jump-analysis/3.1.overlapping_compounds.py
> +# # Finding overlapping compounds
A good point! yes!

2024-04-16 15:28 UTC, axiomcura commented on notebooks/1.data_splits/nbconverted/1.data_splits.py
> +from src.utils import split_meta_and_features  # noqa
Fixed in eab5427aec2d36eb9dfb6b892deb63aa568d60f0

2024-04-17 03:17 UTC, axiomcura commented
@gwaybio I have reviewed all comments, but I will keep this PR open until finalized! Thank you

2024-04-17 22:26 UTC, merged